# Fuerza redeploy con ajuste menor
services:
  - type: web
    name: MemeRep-Webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webhook_server:app --bind 0.0.0.0:$PORT

